apiVersion: v1
kind: Service
metadata:
  name: ai-voice-assistant-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: ai-voice-assistant
